module Hunch.Types where

--------------------------------------------------------------------------------

             -------------- Alphabetical 
data Writing = Latin
             | Cyrillic
             | Greek
             | Armenian
             | Georgian
             -------------- Syllabic
             | Hanzi
             | Kanji
             -------------- Abjad
             | Hebrew
             | Arabic
             -------------- Abugida  
             | IndicN
             | IndicS
             | Ethiopic
             | Thaana
             | Hangul
             | Other
  deriving (Show, Eq, Ord)


data Lang = Afrikaans
          | Albanian
          | Amharic
          | Arabic
          | Armenian
          | Azerbaijani
          | Basque
          | Belarusian
          | Bengali
          | Bosnian
          | Bulgarian
          | Catalan
          | Cebuano
          | Chichewa
          | Chinese
          | Corsican
          | Croatian
          | Czech
          | Danish
          | Dutch
          | English
          | Esperanto
          | Estonian
          | Filipino
          | Finnish
          | French
          | Frisian
          | Galician
          | Georgian
          | German
          | Greek
          | Gujarati
          | HaitianCreole
          | Hausa
          | Hawaiian
          | Hebrew
          | Hindi
          | Hmong
          | Hungarian
          | Icelandic
          | Igbo
          | Indonesian
          | Irish
          | Italian
          | Japanese
          | Javanese
          | Kannada
          | Kazakh
          | Khmer
          | Korean
          | Kurdish
          | Kyrgyz
          | Lao
          | Latin
          | Latvian
          | Lithuanian
          | Luxembourgish
          | Macedonian
          | Malagasy
          | Malay
          | Malayalam
          | Maltese
          | Maori
          | Marathi
          | Mongolian
          | Myanmar
          | Nepali
          | Norwegian
          | Pashto
          | Persian
          | Polish
          | Portuguese
          | Punjabi
          | Romanian
          | Russian
          | Samoan
          | ScotsGaelic
          | Serbian
          | Sesotho
          | Shona
          | Sindhi
          | Sinhala
          | Slovak
          | Slovenian
          | Somali
          | Spanish
          | Sundanese
          | Swahili
          | Swedish
          | Tajik
          | Tamil
          | Telugu
          | Thai
          | Turkish
          | Ukrainian
          | Urdu
          | Uzbek
          | Vietnamese
          | Welsh
          | Xhosa
          | Yiddish
          | Yoruba
          | Zulu
          deriving (Show, Eq, Ord)
 
